apiVersion: apps/v1
kind: Deployment
metadata:
  name: transferciniz-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transferciniz-api
  template:
    metadata:
      labels:
        app: transferciniz-api
    spec:
      containers:
        - name: transferciniz-api
          image: registry.digitalocean.com/transferciniz-container/transferciniz-api:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: "true"
          command: ["dotnet", "Transferciniz.API.dll"]
