apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREE0TVRjeApOakk0TWpCYUZ3MDBOREE0TVRjeE5qSTRNakJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNmdvZUgyTzVwaU5CZHZrTHVpMnQ5MVlmd0EzTVdkWGcySThXKzJNZ3hSaDdSaUJjSgp0d0pLU25MTFNIck12cGtkSTlkbXkyeFFlUnVqNzduUkFiYlJ6eGxwQjJjMEtBUVdYNStpSzQ0SzBTY3BMYUEwCjAyN1NkUStmL0o4VlhLSS9iSDdPVjZJRmJTY0I5RURLb2cxOC9OOUZxWllLS1MzSEgybHRBZjhJNG1JSFpkMHkKblhNN1VPRzF2clFJbDM4aWw1RjlodGRNdE9RMEhJc09RYlQ5eWRqMzhJaFJzL1RGRWVyY21qKzBDeUFZV1lIRQpuanVkS29GMEZjd3hzbWxwTERnUnlpaTd4NlA3TjZSbHVxUTJEcHcza0FCSElocFk0S2dWQWEwamFBb29lcG1kCmJhOEt4VEF0N0M4ZlA4Q0dYeXFtNm9zTllNSjdnUkg0TS9YbkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlE3K3ZhcUEyblV0S096UHZPegpacHhXTit5c056QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXWXprUzlJUWl5Q2M1Y01LRGM2WU9oUU95dEkrCkQ2MmxOeEc3WmtLVXpJNm5kUHRGOWpDTjk4ZEFLS3ZURXh2cFQycTNUODUwREg0cjB6UEJVTG9JYldrSnM1WEYKT0I1Z1plVGR4cVZGTjNUQXo3UGl3c1NZb3h5a1U3SEJ2MWlLR2t2RVZmd2FzYmFjVGNOc0Z4a1dYVmpWNEEycAo1NDNCbVFBN0ZDQnhOUFNnQVZ6K3VPRXBRbU9pejRWQUVJYVpJdlR3NlV6WW1obVF6RWlhc0tsWUZkUE1mTjdnCjdOdW5aQ21qWlYxN2J1WTRlbUIrT0xpdW1hcmh2RG5RaEl5WUpiMkd2VlZTUU0xUFNtaHpNVmMyWFdDYmVWNVUKMlJoYjYvbStQRm05QlVjNFNEaWRkaFozaG1LejRPUURnOTNlR1JDQUNVYmt4dW01YmF2MENYcDNZQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://9a6d1c5f-3a50-4985-a123-bfd6633d24b5.k8s.ondigitalocean.com
    name: do-lon1-transferciniz-k8s-development
contexts:
  - context:
      cluster: do-lon1-transferciniz-k8s-development
      user: do-lon1-transferciniz-k8s-development-admin
    name: do-lon1-transferciniz-k8s-development
current-context: do-lon1-transferciniz-k8s-development
kind: Config
preferences: {}
users:
  - name: do-lon1-transferciniz-k8s-development-admin
    user:
      token: dop_v1_87ee14f3bc742d20339ff0aeada0bc96c8993cb0f218f3e16a6d9d2fe6432f62
