apiVersion: v1
kind: Service
metadata:
  name: transferciniz-api-service
spec:
  type: LoadBalancer
  selector:
    app: transferciniz-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
